[package]
name = "rqbit"
description = "A bittorent client"
version = "0.1.0"
authors = ["Igor Katson <igor.katson@gmail.com>"]
edition = "2018"

[features]
default = ["sha1-openssl"]
sha1-system = ["librqbit/sha1-system"]
sha1-openssl = ["librqbit/sha1-openssl"]
sha1-rust = ["librqbit/sha1-rust"]

[dependencies]
librqbit = {path="../librqbit", default-features=false}
dht = {path="../dht"}
tokio = {version = "1", features = ["macros", "sync", "rt-multi-thread", "io-std"]}
anyhow = "1"
clap = "3.0.0-beta.2"
log = "0.4"
pretty_env_logger = "0.4"
reqwest = "0.11"
regex = "1"
futures = "0.3"
parse_duration = "2"
size_format = "1"

[dev-dependencies]
futures = {version = "0.3"}
